name: EnterpriseApp
options:
  bundleIdPrefix: com.enterprise
targets:
  EnterpriseApp:
    type: application
    platform: iOS
    deploymentTarget: "17.0"
    sources: [App]
    settings:
      base:
        GENERATE_INFOPLIST_FILE: YES
        INFOPLIST_KEY_UILaunchScreen_Generation: YES
    dependencies:
      - package: EnterpriseAppModules
        product: FeatureAuth
      - package: EnterpriseAppModules
        product: FeatureOrganization
      - package: EnterpriseAppModules
        product: FeatureDashboard
      - package: EnterpriseAppModules
        product: AppNetwork
      - package: EnterpriseAppModules
        product: Domain
      - package: EnterpriseAppModules
        product: AppData
      - package: EnterpriseAppModules
        product: DesignSystem
      - package: EnterpriseAppModules
        product: FeatureInbox
      - package: EnterpriseAppModules
        product: FeatureMessaging
packages:
  EnterpriseAppModules:
    path: EnterpriseAppModules
