name: EnterpriseApp
options:
  bundleIdPrefix: com.enterprise
targets:
  EnterpriseApp:
    type: application
    platform: iOS
    deploymentTarget: "17.0"
    sources: [App]
    dependencies:
      - package: EnterpriseAppModules
        product: FeatureAuth
      - package: EnterpriseAppModules
        product: FeatureDashboard
      - package: EnterpriseAppModules
        product: AppNetwork
      - package: EnterpriseAppModules
        product: Domain
      - package: EnterpriseAppModules
        product: AppData
      - package: EnterpriseAppModules
        product: DesignSystem
packages:
  EnterpriseAppModules:
    path: EnterpriseAppModules
